# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-21 13:44
from __future__ import unicode_literals

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityForKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('addres', django_google_maps.fields.AddressField(max_length=200)),
                ('aditional_information', models.TextField(blank=True, verbose_name='Place Description')),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodForKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTypeForKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_per_person', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('activities', models.ManyToManyField(to='centro.ActivityForKnowledge')),
                ('center', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='centro.Center')),
                ('food', models.ManyToManyField(to='centro.FoodForKnowledge')),
                ('group_type', models.ManyToManyField(to='centro.GroupTypeForKnowledge')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='centro.Center')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centro.Center')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.User')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observation', models.TextField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.Center')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Service')),
            ],
        ),
        migrations.CreateModel(
            name='TransportForKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='knowledge',
            name='transport',
            field=models.ManyToManyField(to='centro.TransportForKnowledge'),
        ),
        migrations.AddField(
            model_name='center',
            name='service',
            field=models.ManyToManyField(through='centro.ServiceCenter', to='servicio.Service'),
        ),
        migrations.AddField(
            model_name='center',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center', to='usuario.User'),
        ),
    ]
