# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 23:08
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0002_auto_20161205_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
