# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20161211_1642'),
        ('centro', '0004_auto_20161205_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='service',
            field=models.ManyToManyField(to='servicio.Service'),
        ),
    ]
