# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20161211_1648'),
        ('centro', '0005_center_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='center',
            name='service',
        ),
        migrations.AddField(
            model_name='centerservices',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.Center'),
        ),
        migrations.AddField(
            model_name='centerservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='centerservices',
            unique_together=set([('center', 'service')]),
        ),
    ]
