# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20161211_1648'),
        ('centro', '0007_auto_20161211_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='service',
            field=models.ManyToManyField(through='centro.CenterService', to='servicio.Service'),
        ),
    ]
