# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_user_type'),
        ('centro', '0008_center_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.User'),
        ),
    ]
