# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0010_center_aditional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.User'),
        ),
    ]
