# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0014_auto_20170122_0904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centerservice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='centerservice',
            name='center',
        ),
        migrations.RemoveField(
            model_name='centerservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='center',
            name='service',
        ),
        migrations.DeleteModel(
            name='CenterService',
        ),
    ]
