# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0016_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='food',
            field=models.CharField(choices=[('0', 'Comida Típica'), ('1', 'Platos a la Carta'), ('2', 'Menú del día'), ('3', 'No se vende comida')], default=1, max_length=1),
        ),
    ]
