# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 16:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0018_auto_20170707_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('0', 'Niños'), ('1', 'Adultos'), ('2', 'Adultos Mayores'), ('4', 'Niños y Adultos'), ('5', 'Niños y Adultos Mayores'), ('6', 'Adultos y Adultos Mayores'), ('7', 'Niños, Adultos y Adultos Mayores')], default=1, max_length=1)),
                ('money_per_person', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('activities', models.CharField(choices=[('0', 'Observar Paisajes'), ('1', 'Senderismo'), ('2', 'Contacto con la Naturaleza'), ('3', 'Visita Cultura'), ('4', 'Piscinas, Canchas, etc')], default=4, max_length=1)),
                ('transport', models.CharField(choices=[('0', 'Transporte Público'), ('1', 'Transporte Privado'), ('2', 'Transporte Público y Privado')], default=0, max_length=1)),
                ('food', models.CharField(choices=[('0', 'Comida Típica'), ('1', 'Platos a la Carta'), ('2', 'Menú del día'), ('3', 'No se vende comida')], default=1, max_length=1)),
                ('extreme_sport', models.BooleanField(default=False)),
                ('sport_fishing', models.BooleanField(default=False)),
                ('night_bar', models.BooleanField(default=True)),
                ('has_lodging', models.BooleanField(default=False)),
            ],
        ),
    ]
