# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_user_reason_to_validate'),
        ('centro', '0023_auto_20170725_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityForKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodForKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupTypeForKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='extreme_sport',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='food',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='group_type',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='has_lodging',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='money_per_person',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='night_bar',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='sport_fishing',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='transport',
        ),
        migrations.AddField(
            model_name='poll',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centro.Center'),
        ),
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.User'),
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='food',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='group_type',
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='transport',
            field=models.CharField(choices=[('0', 'Transporte Público'), ('1', 'Transporte Privado')], default='0', max_length=32),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='activities',
            field=models.ManyToManyField(to='centro.ActivityForKnowledge'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='food',
            field=models.ManyToManyField(to='centro.FoodForKnowledge'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='group_type',
            field=models.ManyToManyField(to='centro.GroupTypeForKnowledge'),
        ),
    ]
