# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0026_auto_20170811_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportForKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
    ]
