# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0027_transportforknowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='transport',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='transport',
            field=models.ManyToManyField(to='centro.TransportForKnowledge'),
        ),
    ]
