# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0028_auto_20170811_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
