# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0029_poll_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
