# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0030_auto_20170811_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='extreme_sport',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='has_lodging',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='night_bar',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='sport_fishing',
        ),
    ]
