# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0031_auto_20170824_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
