# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-12 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0009_auto_20170911_1903'),
        ('centro', '0032_center_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.Center')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Service')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='service',
            field=models.ManyToManyField(through='centro.ServiceCenter', to='servicio.Service'),
        ),
    ]
