# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0034_auto_20170911_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='observation',
            field=models.TextField(blank=True),
        ),
    ]
