# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0035_auto_20170920_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(default='Generic Description', max_length=255),
            preserve_default=False,
        ),
    ]
