# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0037_auto_20171016_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='centro.Center'),
        ),
    ]
