# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('u', 'Usuario Normal'), ('c', 'Usuario Centro')], default='u', max_length=1),
        ),
    ]
