# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('as_premium', 'as_premium'),)},
        ),
    ]
