# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_add_center',
            field=models.BooleanField(default=False),
        ),
    ]
