# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_user_has_add_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reason_to_validate',
            field=models.TextField(blank=True),
        ),
    ]
