# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-21 13:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default=models.CharField(max_length=256, unique=True), editable=False, null=True, populate_from='name', unique=True)),
            ],
        ),
    ]
