# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='observation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
