# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20161211_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='service',
            name='observation',
        ),
    ]
