# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_auto_20170410_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Piscinas', 'Piscinas'), ('Balneario', 'Balneario'), ('Mirador', 'Mirador'), ('Senderismo', 'Senderismo'), ('Canchas Deportivas', 'Canchas Deportivas'), ('Mirador', 'Mirador'), ('Bar Nocturno', 'Bar Nocturno'), ('Alojamiento', 'Alojamiento'), ('Restaurante', 'Resturante'), ('Cabañas', 'Cabañas'), ('Asadero', 'Asadero'), ('Pesca Deportiva', 'Pesca Deportiva'), ('Servicios Culturales', 'Servicios Culturales'), ('Dique', 'Dique'), ('Canotaje', 'Canotaje'), ('Rafting', 'Rafting'), ('Canopy', 'Canopy')], max_length=256),
        ),
    ]
