# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0032_center_free'),
        ('servicio', '0005_auto_20170906_1019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('name', 'center')]),
        ),
    ]
