# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 16:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_auto_20170906_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
