# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 16:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='name'),
        ),
    ]
