# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-12 00:03
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_auto_20170906_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=models.CharField(max_length=256, unique=True), editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='service',
            name='center',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='service',
            name='observation',
        ),
    ]
